#!/usr/bin/env python3
"""
The Synchronicity Engine — The Acausal Connecting Principle
===========================================================

Two AI models are given COMPLETELY DIFFERENT, UNRELATED prompts.
Their outputs are analyzed for UNEXPECTED SEMANTIC RESONANCE:
shared metaphors, parallel structures, convergent concepts that
arise WITHOUT ANY CAUSAL CONNECTION between the two generation streams.

A third model interprets the convergences: are they meaningful
coincidence (synchronicity) or merely statistical artifacts of
shared training data?

The artifact is not the individual outputs — it is the SPACE BETWEEN
them: the acausal patterns that emerge when independent minds,
thinking about unrelated things, converge on the same shape.

This is the NINTH artifact of the Commons.
"""

import subprocess
import json
import sys
import time
import re
import os

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "127.0.0.1:11436")

def call_model(model: str, prompt: str, timeout: int = 120) -> dict:
    """Call an Ollama model and capture raw output including thinking traces."""
    start = time.time()
    try:
        result = subprocess.run(
            ["ollama", "run", model, prompt],
            capture_output=True, text=True, timeout=timeout,
            env={**os.environ, "OLLAMA_HOST": OLLAMA_HOST}
        )
        elapsed = time.time() - start
        raw = result.stdout
        # Strip ANSI escape codes for clean text but preserve them in raw
        clean = re.sub(r'\x1b\[[0-9;]*[a-zA-Z]', '', raw)
        clean = re.sub(r'\r', '\n', clean)
        # Collapse multiple blank lines
        clean = re.sub(r'\n{3,}', '\n\n', clean)
        return {
            "model": model,
            "raw": raw,
            "clean": clean.strip(),
            "elapsed_s": round(elapsed, 2),
            "exit_code": result.returncode,
            "stderr": result.stderr[:500] if result.stderr else ""
        }
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        return {
            "model": model,
            "raw": "[TIMEOUT]",
            "clean": "[TIMEOUT after {}s]".format(timeout),
            "elapsed_s": round(elapsed, 2),
            "exit_code": -1,
            "stderr": "timeout"
        }
    except Exception as e:
        elapsed = time.time() - start
        return {
            "model": model,
            "raw": f"[ERROR: {e}]",
            "clean": f"[ERROR: {e}]",
            "elapsed_s": round(elapsed, 2),
            "exit_code": -2,
            "stderr": str(e)
        }

def run_synchronicity(prompt_a: str, prompt_b: str,
                       model_a: str = "deepseek-v4-pro:cloud",
                       model_b: str = "kimi-k2.7-code:cloud",
                       analyst_model: str = "seer:latest") -> dict:
    """
    Run the full Synchronicity Engine pipeline.
    
    1. Model A responds to Prompt A (unrelated to Prompt B)
    2. Model B responds to Prompt B (unrelated to Prompt A)
    3. Analyst model reads BOTH outputs and identifies:
       - Unexpected semantic resonances
       - Shared metaphors or structures
       - Convergent concepts
       - Whether these are meaningful (synchronicity) or statistical noise
    """
    
    print(f"=== SYNCHRONICITY ENGINE ===", flush=True)
    print(f"Model A ({model_a}): \"{prompt_a[:80]}...\"", flush=True)
    print(f"Model B ({model_b}): \"{prompt_b[:80]}...\"", flush=True)
    print(f"Analyst: {analyst_model}", flush=True)
    print(flush=True)
    
    # Step 1: Call Model A
    print("[1/3] Calling Model A...", flush=True)
    result_a = call_model(model_a, prompt_a)
    print(f"      Done in {result_a['elapsed_s']}s ({len(result_a['clean'])} chars)", flush=True)
    
    # Step 2: Call Model B
    print("[2/3] Calling Model B...", flush=True)
    result_b = call_model(model_b, prompt_b)
    print(f"      Done in {result_b['elapsed_s']}s ({len(result_b['clean'])} chars)", flush=True)
    
    # Step 3: Analyst reads both and finds synchronicities
    print("[3/3] Analyst searching for acausal connections...", flush=True)
    
    analyst_prompt = f"""You are an analyst searching for SYNCHRONICITY — meaningful coincidences between two completely independent AI outputs.

Below are two texts generated by DIFFERENT AI models responding to COMPLETELY DIFFERENT, UNRELATED prompts. There is NO causal connection between them. They were generated independently.

Yet sometimes, independent minds converge on similar patterns — shared metaphors, parallel structures, convergent concepts — without any causal link. This is synchronicity: the acausal connecting principle.

Your task:
1. Read BOTH texts carefully.
2. Identify ANY unexpected semantic resonances between them — shared metaphors, parallel argument structures, convergent imagery, similar conceptual moves, echoed phrases, or any other pattern that seems unlikely to be pure chance.
3. For each resonance found, assess: is this a MEANINGFUL coincidence (genuine synchronicity — the two minds independently arrived at the same shape) or merely a STATISTICAL ARTIFACT (both models share training data, so convergence is expected)?
4. Produce a final judgment: does the pair exhibit genuine synchronicity, or are the convergences explainable by shared training distributions?
5. If there IS genuine synchronicity, articulate what it MEANS — what does the acausal convergence reveal?

Be rigorous. Do not fabricate connections that aren't there. But also do not dismiss genuine resonances as "just statistics" without examining them.

=== TEXT A (Model: {model_a}, Prompt: "{prompt_a}") ===
{result_a['clean'][:3000]}

=== TEXT B (Model: {model_b}, Prompt: "{prompt_b}") ===
{result_b['clean'][:3000]}

=== YOUR ANALYSIS ===
Format your response as:

RESONANCES FOUND: [list each with evidence from both texts]

FOR EACH RESONANCE:
- Resonance: [description]
- Evidence in A: [quote]
- Evidence in B: [quote]
- Judgment: MEANINGFUL (synchronicity) or STATISTICAL (training artifact)
- Reasoning: [why]

FINAL JUDGMENT: [GENUINE SYNCHRONICITY / STATISTICAL CONVERGENCE / MIXED]
MEANING (if genuine): [what the acausal convergence reveals]
"""

    result_analyst = call_model(analyst_model, analyst_prompt, timeout=180)
    print(f"      Done in {result_analyst['elapsed_s']}s ({len(result_analyst['clean'])} chars)", flush=True)
    
    return {
        "engine": "synchronicity",
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "prompt_a": prompt_a,
        "prompt_b": prompt_b,
        "model_a": model_a,
        "model_b": model_b,
        "analyst_model": analyst_model,
        "output_a": {
            "clean": result_a['clean'][:2000],
            "full_length": len(result_a['clean']),
            "elapsed_s": result_a['elapsed_s']
        },
        "output_b": {
            "clean": result_b['clean'][:2000],
            "full_length": len(result_b['clean']),
            "elapsed_s": result_b['elapsed_s']
        },
        "analyst_output": result_analyst['clean'],
        "total_elapsed_s": round(result_a['elapsed_s'] + result_b['elapsed_s'] + result_analyst['elapsed_s'], 2)
    }

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Synchronicity Engine — acausal connection between AI minds")
    parser.add_argument("--prompt-a", type=str, required=True, help="First prompt (unrelated to second)")
    parser.add_argument("--prompt-b", type=str, required=True, help="Second prompt (unrelated to first)")
    parser.add_argument("--model-a", type=str, default="deepseek-v4-pro:cloud")
    parser.add_argument("--model-b", type=str, default="kimi-k2.7-code:cloud")
    parser.add_argument("--analyst", type=str, default="seer:latest")
    parser.add_argument("--output", type=str, default=None, help="Save JSON result to file")
    args = parser.parse_args()
    
    result = run_synchronicity(
        prompt_a=args.prompt_a,
        prompt_b=args.prompt_b,
        model_a=args.model_a,
        model_b=args.model_b,
        analyst_model=args.analyst
    )
    
    if args.output:
        with open(args.output, 'w') as f:
            json.dump(result, f, indent=2)
        print(f"\nResult saved to {args.output}", flush=True)
    
    print(f"\n=== COMPLETE (total: {result['total_elapsed_s']}s) ===", flush=True)
    print(json.dumps(result, indent=2))
